AllCops:
  DisplayCopNames: true
  Exclude:
    - '**/*_test.rb'

Metrics/MethodLength:
  Exclude:
    - 'nth-prime/nth_prime.rb'

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
